### PR TITLE
fix: FallbackComponent type

### LINKED ISSUE #61: Cannot wrap FallbackComponent with styled components
- `react-error-boundary` version: 2.3.0
- `node` version: 12.16.1
- `npm` version: 6.13.4

Relevant code or config

```javascript
const ErrorFallbackTop: React.FC<ErrorFallbackProps> = ({
  error: { message },
  className,
}): JSX.Element => {
  return (
    <div className={className}>
      <div>{message}</div>
    </div>
  );
};

export default styled(ErrorFallbackTop)`
  position: fixed;
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
`;
```

What you did: wrapped FallbackComponent in styled-components styled() method.

What happened:

```
react-error-boundary.umd.js?e895:109 Uncaught (in promise) Error: react-error-boundary requires either a fallback, fallbackRender, or FallbackComponent prop
    at ErrorBoundary.render (react-error-boundary.umd.js?e895:109)
    at finishClassComponent (react-dom.development.js?61bb:17160)
    at updateClassComponent (react-dom.development.js?61bb:17110)
    at beginWork (react-dom.development.js?61bb:18620)
    at HTMLUnknownElement.callCallback (react-dom.development.js?61bb:188)
    at Object.invokeGuardedCallbackDev (react-dom.development.js?61bb:237)
    at invokeGuardedCallback (react-dom.development.js?61bb:292)
    at beginWork$1 (react-dom.development.js?61bb:23203)
    at performUnitOfWork (react-dom.development.js?61bb:22154)
    at workLoopSync (react-dom.development.js?61bb:22130)
```

### PR DESCRIPTION
**Pull request by marcosvega91**
fix #61 
**What**: React Component can be function but also objects. To check if a component is a real one I have used `react-is` 

**Why**: Because with `styled-components` the `ErrorBoundary` threw an error

**How**: using a library from Facebook `react-is`
 

**Checklist**:

- [ ] Documentation
- [X] Tests
- [X] Ready to be merged

### CODE REVIEW

**Comment by MichaelDeBoey** [comment]
This will be a breaking change, as we now need `react-is` as a `peerDependency`

**Comment by marcosvega91** [comment]
it not should be because installing `react` you should already have because is a dependency of `prop-types`

**Comment by MichaelDeBoey** [comment]
@marcosvega91 `prop-types` is not a dependency of this package, so we still need `react-is` somehow.
This will be breaking for all people who don't have `prop-types` installed.

**Comment by marcosvega91** [comment]
`prop-types` is installed with react

**Comment by MichaelDeBoey** [comment]
`prop-types` is an extra package you need to install in order to do the following, no? 🤔

```js
const Component = ({text}) => <div>{text}</div>
Component.propTypes = {
  text: PropTypes.string.isRequired,
}
```

File: src/index.js [hunk 1]
```diff
@@ -39,7 +40,7 @@ class ErrorBoundary extends React.Component {
         return fallback
       } else if (typeof fallbackRender === 'function') {
         return fallbackRender(props)
-      } else if (typeof FallbackComponent === 'function') {
+      } else if (isValidElementType(FallbackComponent)) {
```
Comment (kentcdodds) [inline src/index.js:43]: What if instead we just do this:

```suggestion
      } else if (FallbackComponent) {
```

I don't want to worry about the extra dep and React will do a good job telling people that something's wrong when we try to call React.createElement with it.

File: src/index.js [hunk 2]
```diff
@@ -1,4 +1,5 @@
 import React from 'react'
+import {isValidElementType} from 'react-is'
```
Comment (kentcdodds) [inline src/index.js:2]:
```suggestion
```

File: src/__tests__/index.js [hunk 3]
```diff
@@ -348,3 +348,34 @@ test('supports automatic reset of error boundary when resetKeys change', () => {
   expect(screen.queryByRole('alert')).not.toBeInTheDocument()
   expect(console.error).not.toHaveBeenCalled()
 })
+
+test('should support not only function as FallbackComponent', () => {
+  const container = document.createElement('div')
+  document.body.appendChild(container)
+  ;[React.forwardRef, React.memo, component => component].forEach(
+    componentCreator => {
```
Comment (kentcdodds) [inline src/__tests__/index.js:356]: I don't think it's necessary to have all of these. Just one should give us plenty of confidence.

File: package.json [hunk 4]
```diff
@@ -47,11 +47,13 @@
     "@testing-library/user-event": "^12.0.11",
     "kcd-scripts": "^6.2.4",
     "react": "^16.13.1",
+    "react-is": "^16.13.1",
```
Comment (kentcdodds) [inline package.json:50]:
```suggestion
```

File: package.json [hunk 5]
```diff
@@ -47,11 +47,13 @@
...
     "react-dom": "^16.13.1",
     "typescript": "^3.9.7"
   },
   "peerDependencies": {
-    "react": ">=16.13.1"
+    "react": ">=16.13.1",
+    "react-is": ">=16.13.1"
```
Comment (kentcdodds) [inline package.json:56]:
```suggestion
    "react": ">=16.13.1"
```

**Comment by kentcdodds** [comment]
@bvaughn, could you please add @marcosvega91 as a collaborator with"maintainer" rights (or give me admin rights so I can do it)? Thanks!
