### PR TITLE
fix: avoid double-render

### LINKED ISSUE #66: Update state with getDerivedStateFromError rather than componentDidCatch
The `componentDidCatch` lifecycle method exists for side effects (e.g. logging). Using `componentDidCatch` to update state and re-render after an error is an anti-pattern and future versions of React will likely skip over error boundaries that don't define `getDerivedStateFromError`.

When ["error boundaries" were first introduced in v16.0](https://reactjs.org/blog/2017/07/26/error-handling-in-react-16.html), `componentDidCatch` was the only API available. The `static getDerivedStateFromError` API was added in v16.6 to improve the error handling process to avoid the necessity to render an intermediate, broken state before calling the commit-phase `componentDidCatch` hook and *rendering again* to show fallback UI.

I don't use this package for anything so I had forgotten about it being outdated until this morning.

~~Note that this would technically be a breaking change since it would raise the minimum version of React supported from 16.0 to 16.6.~~ Looks like @kentcdodds already raised the "react" dependency to 16.13+ via #46 😅  Guess this wouldn't be a breaking change after all then.

### PR DESCRIPTION
**Pull request by kentcdodds**
**What**: fix: avoid double-render

**Why**: Closes #66 and Closes #67

**How**:

- Remove the `setState` call in `componentDidCatch`
- Ensure that the cDU only resets if the component is updated *after* the first update with an error.

**Checklist**:

- [x] Documentation
- [x] Tests
- [x] Ready to be merged
      

BREAKING CHANGE: This removes the `componentStack` in the props given to the `FallbackComponent` and `fallbackRender`

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -3,52 +3,55 @@ import React from 'react'
...
+  }
+
+  reset() {
+    this.updatedWithError = false
     this.setState(initialState)
   }
 
   componentDidCatch(error, info) {
-    this.props.onError?.(error, info?.componentStack)
-    this.setState({info})
```
Comment (bvaughn) [inline src/index.js:20]: Nice

File: src/index.js [hunk 2]
```diff
@@ -3,52 +3,55 @@ import React from 'react'
...
-      changedArray(prevProps.resetKeys, resetKeys)
-    ) {
+
+    // There's an edge case where if the thing that triggered the error
+    // happens to *also* be in the resetKeys array, we'd end up resetting
+    // the error boundary immediately. This would likely trigger a second
+    // error to be thrown.
+    // So we make sure that we don't check the resetKeys on the first call
+    // of cDU after the error is set
+    if (error !== null && !this.updatedWithError) {
```
Comment (bvaughn) [inline src/index.js:38]: I don't think I fully understand why the `resetKeys` feature is helpful, or what the purpose of `onResetKeysChange` does– but the way you're using the `updatedWithError` instance attribute looks safe (since it's only modified during the commit phase or during an imperative reset "action".

File: src/index.js [hunk 3]
```diff
@@ -3,52 +3,55 @@ import React from 'react'
...
+      this.updatedWithError = true
+      return
+    }
+
+    if (error !== null && changedArray(prevProps.resetKeys, resetKeys)) {
       this.props.onResetKeysChange?.(prevProps.resetKeys, resetKeys)
-      this.setState(initialState)
+      this.reset()
```
Comment (bvaughn) [inline src/index.js:45]: Shouldn't this be calling `resetErrorBoundary`? Otherwise you won't call `props.onReset`.

**Review by bvaughn — COMMENTED** [review]
Thanks for tackling this and removing the second render 😁

File: src/index.js (hunk 2 above)
Comment (kentcdodds) [reply src/index.js:38]: Yeah, it's actually quite helpful. Here's an example of it in action: https://react-hooks.netlify.app/6 (It's the Extra Credit 8, which you can play with here: https://react-hooks.netlify.app/isolated/final/06.extra-8.js)

Basically, if there's a property that you anticipate resulting in an error to be thrown, then you can put it in the `resetKeys` array and after an error has been thrown, if any values in the array changes then it will be reset automatically.

Here's a gif that demonstrates what this does. With the reset keys, the error boundary is automatically reset when I change the pokemon name:

Screen Recording 2020-09-11 at 9 15 39 AM

File: src/index.js (hunk 3 above)
Comment (kentcdodds) [reply src/index.js:45]: `props.onReset` will be called only for when `this.resetErrorBoundary` is called (presumably the end-user clicked a button you rendered in your fallback that triggered this). `props.onResetKeysChange` will be called only for when the reset happened due to a change in the `resetKeys`. It's possible these will both be set to the same function, but I think having the distinction could be helpful which is why they're different functions.

I'm open to your feedback on this though. Great opportunity to break things since we'll be pushing a major version bump.

**Review by kentcdodds — COMMENTED** [review]
Thanks for taking the time to review this and provide feedback.

File: src/index.js (hunk 3 above)
Comment (bvaughn) [reply src/index.js:45]: Hm. I see what you mean, but I would have assumed (if I were using this component) that `onReset` was called *any time the boundary reset* (for any reason) and `onResetKeysChange` was called *any time the reset keys changed* and those things are decoupled (because one can happen without the other).

How do you actually observe when a reset happens because of a key change? (Using `onResetKeysChange` won't be sufficient to tell you this, will it)?

File: src/index.js (hunk 2 above)
Comment (bvaughn) [reply src/index.js:38]: Thanks for elaborating. The concept seems a bit odd to me, but not necessarily in a *bad* way. It could just be because it's a different way of thinking about using the boundary than would have occurred to me.

I guess it's roughly similar to using an id-based `key` or something to completely reset a subtree between view changes.

Anyway :smile: it doesn't look like it would cause problems. (Instance properties can sources of subtle side effects but I think this one looks fine.)

File: src/index.js (hunk 3 above)
Comment (kentcdodds) [reply src/index.js:45]: > How do you actually observe

Is "you" referring to the developer user or library author? 😅

For the developer, they'll know because `onResetKeysChange` will be called. The lib author knows because we do this check in cDU to compare the previous `resetKeys` with the next ones.

Comment (bvaughn) [reply src/index.js:45]: I was referring to the library user.

And, right. I forgot that we only check and call `onResetKeysChange` if the `error !== null` (because intuitively, I still think keys changing is separate from resetting).

Anyway, maybe this isn't a valuable conversation to continue. It just seemed a little unintuitive to me, but I'm only one person.

Comment (kentcdodds) [reply src/index.js:45]: It's quite possible this particular feature is a bit niche. But it's definitely solved real problems for me so that's why I think it's worth the added complexity 😅

Thanks for your feedback @bvaughn! Always appreciate your time :)

**Comment by ranisalt** [comment]
Great, now how do I get the component stack? It was essential for me.

**Comment by kentcdodds** [comment]
Use the old version or use the onError handler. Or you could write your own error boundary.

**Comment by bvaughn** [comment]
@ranisalt This component is very small. If you have a use case it doesn't solve- fork it.

**Comment by ranisalt** [comment]
I see. A combination of `onError` and `useState` solves this. Thanks :+1:

**Comment by karlhorky** [comment]
@ranisalt how exactly did you do this? Is it similar to the code below from [this gist]()?

```jsx
export default function MyApp({ Component, pageProps }: { Component: any; pageProps: any }) {
  // ReactErrorBoundary doesn't pass in the component stack trace.
  // Capture that ourselves to pass down via render props
  const [errorInfo, setErrorInfo] = useState<React.ErrorInfo | null>(null);

  return (
    <React.Fragment>
      <ErrorBoundary
        onError={(error, info) => {
          if (process.env.NODE_ENV === 'production') {
            uploadErrorDetails(error, info);
          }
          setErrorInfo(info);
        }}
        fallbackRender={fallbackProps => {
          return <AppErrorFallback {...fallbackProps} errorInfo={errorInfo} />;
        }}
      >
        <Component {...pageProps} />;
      </ErrorBoundary>
    </React.Fragment>
  );
}
```

**Comment by karlhorky** [comment]
@bvaughn @kentcdodds would you be open to having an example like this in the readme for those who want the component stack trace?

**Comment by kentcdodds** [comment]
That's fine with me. Most of the time the component stack trace is unnecessary, so make a note about that as well 👍

**Comment by king-of-poppk** [comment]
> @ranisalt how exactly did you do this? Is it similar to the code below from this gist?
> 
> ```js
> export default function MyApp({ Component, pageProps }: { Component: any; pageProps: any }) {
>   // ReactErrorBoundary doesn't pass in the component stack trace.
>   // Capture that ourselves to pass down via render props
>   const [errorInfo, setErrorInfo] = useState<React.ErrorInfo | null>(null);
> 
>   return (
>     <React.Fragment>
>       <ErrorBoundary
>         onError={(error, info) => {
>           if (process.env.NODE_ENV === 'production') {
>             uploadErrorDetails(error, info);
>           }
>           setErrorInfo(info);
>         }}
>         fallbackRender={fallbackProps => {
>           return <AppErrorFallback {...fallbackProps} errorInfo={errorInfo} />;
>         }}
>       >
>         <Component {...pageProps} />;
>       </ErrorBoundary>
>     </React.Fragment>
>   );
> }
> ```

This renders twice on error right? Once with the current `error` and the previous `info` (or `undefined` the first time) and once with the current `error` and `info`.

Will this potentially commit or render a transient invalid state?
