### PR TITLE
fix: switch to getDerivedStateFromError to avoid unnecessary rerender

### LINKED ISSUE #66: Update state with getDerivedStateFromError rather than componentDidCatch
The `componentDidCatch` lifecycle method exists for side effects (e.g. logging). Using `componentDidCatch` to update state and re-render after an error is an anti-pattern and future versions of React will likely skip over error boundaries that don't define `getDerivedStateFromError`.

When ["error boundaries" were first introduced in v16.0](https://reactjs.org/blog/2017/07/26/error-handling-in-react-16.html), `componentDidCatch` was the only API available. The `static getDerivedStateFromError` API was added in v16.6 to improve the error handling process to avoid the necessity to render an intermediate, broken state before calling the commit-phase `componentDidCatch` hook and *rendering again* to show fallback UI.

I don't use this package for anything so I had forgotten about it being outdated until this morning.

~~Note that this would technically be a breaking change since it would raise the minimum version of React supported from 16.0 to 16.6.~~ Looks like @kentcdodds already raised the "react" dependency to 16.13+ via #46 😅  Guess this wouldn't be a breaking change after all then.

### PR DESCRIPTION
**Pull request by kentcdodds**
Closes #66

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -30,6 +38,15 @@ class ErrorBoundary extends React.Component {
     const {fallbackRender, FallbackComponent, fallback} = this.props
 
     if (error !== null) {
+      // we'll get a re-render with the error state in getDerivedStateFromError
+      // but we don't have the info yet, so just render null
+      // note that this won't be committed to the DOM thanks to our componentDidCatch
+      // so the user won't see a flash of nothing, so this works fine.
+      // the benefit of doing things this way rather than just putting both the
+      // error and info setState within componentDidCatch is we avoid re-rendering
+      // busted stuff: https://github.com/bvaughn/react-error-boundary/issues/66
```
Comment (bvaughn) [inline src/index.js:47]: This doesn't seem ideal, since we'll still double render (and cause two DOM mutations). My guess is that– for most cases– the component stack won't get rendered anyway. (Heck even the error text itself probably won't be rendered, (since you probably wouldn't want to show those to the end user).

You could always log them to the console in DEV mode using the `onError` prop if you wanted to make it faster to track down errors while iterating on code.

I wonder if we should reconsider this part of the API?

Comment (kentcdodds) [reply src/index.js:47]: Yeah, I don't like this either, but I'm not sure I see much of a drawback because really all this means is that there will be an uncommitted render of null which I don't think is a big deal. Unless I'm missing something.

Comment (kentcdodds) [reply src/index.js:47]: I'm definitely willing to make a major version bump to remove the componentStack.

Comment (bvaughn) [reply src/index.js:47]: > all this means is that there will be an uncommitted render of null

Just to clarify, this would get "committed" (meaning the DOM would get updated) *before* `componentDidCatch` gets called– which would trigger another render+commit loop (which would update the DOM again).

It's not the end of the world, since error boundaries aren't expected to trigger in a tight loop like e.g. list items during scrolling, but it's not ideal to have the intermediate null. Seems like we could tighten it up a bit, if we were being picky 😁

Comment (kentcdodds) [reply src/index.js:47]: Ah, yeah, spices like I was misunderstanding things then. I'll make the breaking change this requires. Thanks!
